SELECT -- QUÉ COLULMNAS (ÚLTIMO EN EJECUTARSE)
FROM - JOIN-- DÓNDE; 1º EN EJECUTARSE
WHERE -- QUÉ FILAS QUIERO (FILTROS SOBRE FILAS); 2º EN EJECUTARSE
GROUP BY -- HACER GRUPOS PARA UN CAMPO O CONJUNTO DE CAMPOS; 3º EN EJECUTARSE
HAVING -- FILTRA GRUPOS QUE CUMPLEN UNA CONDICIÓN; 4º EN EJECUTARSE
ORDER BY -- ORDENO LOS RESULTADOS POR UNA COLUMNA O CONJUNTO DE COLUMNAS

OPERADORES CUANTIFICADORES (CONJUNTO DE RESULTADOS){
	[< ]  SOME -- ALGUNOS
	[<=] ANY -- ALGUNOS
	[> ]
    [>=]  ALL -- TODOS
	[<>]
	[= ]
    
		[NOT]IN -- EL VALOR ESTÁ EN EL CONJUNTO DE RESULTADO.
        
        EXISTS -- EXISTE EL RESULTADO
}
-- Empleados cuyo salario sea igual que el salario de algún empleado del depto 120
SELECT *
FROM empleados
WHERE salarem = some (SELECT salarem
				FROM empleados
                WHERE numde = 120)